apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdsquawk-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birdsquawk
  template:
    metadata:
      labels:
        app: birdsquawk
    spec:
      containers:
      - name: birdsquawk
        image: 1a1a/birdsquawk
---
apiVersion: v1
kind: Service
metadata:
  name: birdsquawk-service
spec:
  selector:
    app: birdsquawk
  ports:
  - name: birdsquawk
    port: 5000
    protocol: TCP
    targetPort: 5000
